/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 dymaxion_map.glb 
Author: ivanavdic (https://sketchfab.com/ivangrozni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dymaxion-map-282a28166e8b46ecbcb16e18bfbac24f
Title: Dymaxion map
*/

import React, { forwardRef, Suspense, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import dmap from '../assets/models/dymaxion_map.glb'

const DymaxionMapModel = forwardRef((props, ref) => { 
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF(dmap)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    
    const action = actions["Scene"];
    if (action) {
      action.play();
    }

    return () => {
      if (action) action.stop();
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.06} rotation={[Math.PI / 2, 0, 0]} position={[-100, -20, -25]}  
      ref={ref}
       name="Sketchfab_Scene">
       <group name="Sketchfab_model"
        //  rotation={[-Math.PI / 2, 0, 0]}
         >
           {/* <group name="09e6533aa6f8451e9f9ec539212d37f0fbx" 
          // rotation={[Math.PI / 2, 0, 0]} 
          scale={0.015}> */}
            {/* <group name="Object_2"> */}
              {/* <group name="RootNode"> */}
                <group name="05" position={[1489.333, 22.703, 45.641]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="05_slika05_0" geometry={nodes['05_slika05_0'].geometry} material={materials.slika05} />
                </group>
                <group name="10" position={[1662.533, 22.693, 45.642]} rotation={[-1.571, 0, 0]} scale={100}>
                  <mesh name="10_slika10_0" geometry={nodes['10_slika10_0'].geometry} material={materials.slika10} />
                </group>
                <group name="13" position={[1835.734, 22.635, 45.642]} rotation={[-1.571, 0.001, 0]} scale={100}>
                  <mesh name="13_slika13_0" geometry={nodes['13_slika13_0'].geometry} material={materials.slika13} />
                </group>
                <group name="20" position={[2008.933, 22.528, 45.641]} rotation={[-Math.PI / 2, 0.001, 0]} scale={100}>
                  <mesh name="20_slika20_0" geometry={nodes['20_slika20_0'].geometry} material={materials.slika20} />
                </group>
                <group name="17" position={[1922.334, 22.586, -4.359]} rotation={[-Math.PI / 2, 0.001, -Math.PI]} scale={100}>
                  <mesh name="17_slika17_0" geometry={nodes['17_slika17_0'].geometry} material={materials.slika17} />
                </group>
                <group name="11" position={[1749.133, 22.674, -4.359]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
                  <mesh name="11_slika11_0" geometry={nodes['11_slika11_0'].geometry} material={materials.slika11} />
                </group>
                <group name="07" position={[1575.933, 22.703, -4.359]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
                  <mesh name="07_slika07_0" geometry={nodes['07_slika07_0'].geometry} material={materials.slika07} />
                </group>
                <group name="04" position={[1402.733, 22.703, -4.359]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
                  <mesh name="04_slika04_0" geometry={nodes['04_slika04_0'].geometry} material={materials.slika04} />
                </group>
                <group name="01" position={[1229.533, 22.703, -4.359]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
                  <mesh name="01_slika01_0" geometry={nodes['01_slika01_0'].geometry} material={materials.slika01} />
                </group>
                <group name="03" position={[1316.133, 22.703, 145.641]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
                  <mesh name="03_slika03_0" geometry={nodes['03_slika03_0'].geometry} material={materials.slika03} />
                </group>
                <group name="06" position={[1489.333, 22.703, 145.641]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
                  <mesh name="06_slika06_0" geometry={nodes['06_slika06_0'].geometry} material={materials.slika06} />
                </group>
                <group name="15" position={[1835.734, 22.615, 145.642]} rotation={[-1.571, 0.001, Math.PI]} scale={100}>
                  <mesh name="15_slika15_0" geometry={nodes['15_slika15_0'].geometry} material={materials.slika15} />
                </group>
                <group name="14" position={[1749.133, 22.635, 195.642]} rotation={[-1.57, 0, 0]} scale={100}>
                  <mesh name="14_slika14_0" geometry={nodes['14_slika14_0'].geometry} material={materials.slika14} />
                </group>
                <group name="16" position={[1922.333, 22.557, 195.642]} rotation={[-1.571, 0.001, 0]} scale={100}>
                  <mesh name="16_slika16_0" geometry={nodes['16_slika16_0'].geometry} material={materials.slika16} />
                </group>
                <group name="12" position={[1749.133, 22.664, -104.359]} rotation={[-1.571, 0, 0]} scale={100}>
                  <mesh name="12_slika12_0" geometry={nodes['12_slika12_0'].geometry} material={materials.slika12} />
                </group>
                <group name="18" position={[1922.334, 22.577, -104.359]} rotation={[-1.571, 0.001, 0]} scale={100}>
                  <mesh name="18_slika18_0" geometry={nodes['18_slika18_0'].geometry} material={materials.slika18} />
                </group>
                <group name="09" position={[1489.333, 22.683, -154.359]} rotation={[-1.571, 0, -Math.PI]} scale={100}>
                  <mesh name="09_slika09_0" geometry={nodes['09_slika09_0'].geometry} material={materials.slika09} />
                </group>
                <group name="19" position={[2008.934, 22.499, -154.359]} rotation={[-1.571, 0.001, -Math.PI]} scale={100}>
                  <mesh name="19_slika19_0" geometry={nodes['19_slika19_0'].geometry} material={materials.slika19} />
                </group>
                <group name="08" position={[1575.932, 22.635, -104.359]} rotation={[-1.571, 0, 0]} scale={100}>
                  <mesh name="08_slika8_0" geometry={nodes['08_slika8_0'].geometry} material={materials.slika8} />
                </group>
                <group name="02" position={[1316.133, 22.203, 45.641]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="02_slika02_0" geometry={nodes['02_slika02_0'].geometry} material={materials.slika02} />
                </group>
                <group name="Armature001" position={[1316.133, 21.203, 45.641]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              {/* </group> */}
            {/* </group> */}
          {/* </group> */}
        </group>
      </group>
    </group>
  )
})

DymaxionMapModel.displayName = 'DymaxionMapModel';

useGLTF.preload(dmap)

const DymaxionMapModelWrapper = forwardRef((props, ref) => (
  <Suspense fallback={null}>
    <DymaxionMapModel ref={ref} {...props} />
  </Suspense>
));

DymaxionMapModelWrapper.displayName = 'DymaxionMapModelWrapper';

export { DymaxionMapModelWrapper as DymaxionMapModel };
