/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 hologram_globe.glb 
Author: ibrahimnasir.dh1022 (https://sketchfab.com/ibrahimnasir.dh1022)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hologram-globe-using-geometry-nodes-0c65d232e07e46be9e8d4c691bc82350
Title: Hologram Globe using Geometry Nodes
*/

import React, { forwardRef, Suspense, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three';
import hologram from '../assets/models/hologram_globe.glb'

const HologramModel = forwardRef((props, ref) => {
  const { currentColor } = props;
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(hologram)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const action = actions["Globe.001|meshNodeAction"];
    if (action) {
      action.play();
    }

    return () => {
      if (action) action.stop();
    };
  }, [actions]);

  const customMaterial = new THREE.MeshPhysicalMaterial({
    metalness: 0,
    roughness: 0.9,
    clearcoat: .9,
    clearcoatRoughness: .9,
    transparent: false,
    side: THREE.DoubleSide,
    wireframe: false,
    color: new THREE.Color(currentColor || 'white'),
  });

  const customMaterial2 = new THREE.MeshPhysicalMaterial({
    metalness: 0,
    roughness: 0.9,
    clearcoat: .9,
    clearcoatRoughness: .9,
    transparent: false,
    side: THREE.DoubleSide,
    wireframe: false,
    color: new THREE.Color('black'),
  });
  
  const customMaterial3 = new THREE.MeshPhysicalMaterial({
    metalness: 0,
    roughness: 0.9,
    clearcoat: .9,
    clearcoatRoughness: .9,
    transparent: false,
    side: THREE.DoubleSide,
    wireframe: false,
    color: new THREE.Color(currentColor || 'white'),
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group ref={ref} name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="GeoGlobefbx" rotation={[Math.PI / 4, 0, 0]} scale={0.24}>
            <group name="Object_2">
              <group name="RootNode">
                <group 
                // name="Globe_001"
                >
                <group 
                name="Globe001" 
                position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0.013]} scale={2.563}>
                  <mesh name="Globe001_BLUE_0" geometry={nodes.Globe001_BLUE_0.geometry} 
                  // material={materials.BLUE}
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_1" geometry={nodes.Globe001_BLUE_0_1.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_2" geometry={nodes.Globe001_BLUE_0_2.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_3" geometry={nodes.Globe001_BLUE_0_3.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_4" geometry={nodes.Globe001_BLUE_0_4.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_5" geometry={nodes.Globe001_BLUE_0_5.geometry}
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_6" geometry={nodes.Globe001_BLUE_0_6.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_7" geometry={nodes.Globe001_BLUE_0_7.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_8" geometry={nodes.Globe001_BLUE_0_8.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                  <mesh name="Globe001_BLUE_0_9" geometry={nodes.Globe001_BLUE_0_9.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial}
                  />
                </group>
                
                <group 
                name="Globe001" 
                position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0.013]} scale={2.363}>
                  <mesh name="Globe001_BLUE_0" geometry={nodes.Globe001_BLUE_0.geometry} 
                  // material={materials.BLUE}
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_1" geometry={nodes.Globe001_BLUE_0_1.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_2" geometry={nodes.Globe001_BLUE_0_2.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_3" geometry={nodes.Globe001_BLUE_0_3.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_4" geometry={nodes.Globe001_BLUE_0_4.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_5" geometry={nodes.Globe001_BLUE_0_5.geometry}
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_6" geometry={nodes.Globe001_BLUE_0_6.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_7" geometry={nodes.Globe001_BLUE_0_7.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_8" geometry={nodes.Globe001_BLUE_0_8.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                  <mesh name="Globe001_BLUE_0_9" geometry={nodes.Globe001_BLUE_0_9.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial2}
                  />
                </group>
                
                <group 
                // name="Globe001" 
                position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0.013]} scale={2.163}>
                  <mesh name="Globe001_BLUE_0" geometry={nodes.Globe001_BLUE_0.geometry} 
                  // material={materials.BLUE}
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_1" geometry={nodes.Globe001_BLUE_0_1.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_2" geometry={nodes.Globe001_BLUE_0_2.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_3" geometry={nodes.Globe001_BLUE_0_3.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_4" geometry={nodes.Globe001_BLUE_0_4.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_5" geometry={nodes.Globe001_BLUE_0_5.geometry}
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_6" geometry={nodes.Globe001_BLUE_0_6.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_7" geometry={nodes.Globe001_BLUE_0_7.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_8" geometry={nodes.Globe001_BLUE_0_8.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                  <mesh name="Globe001_BLUE_0_9" geometry={nodes.Globe001_BLUE_0_9.geometry} 
                  // material={materials.BLUE} 
                  material={customMaterial3}
                  />
                </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

HologramModel.displayName = 'HologramModel';

useGLTF.preload(hologram)

const HologramModelWrapper = forwardRef((props, ref) => (
  <Suspense fallback={null}>
    <HologramModel ref={ref} {...props} />
  </Suspense>
));

HologramModelWrapper.displayName = 'HologramModelWrapper';

export { HologramModelWrapper as HologramModel };
