/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mega_gattling_pea.glb 
Author: Omega.Rabatich (https://sketchfab.com/Omega.Rabatich)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mega-gattling-pea-cfb3e917238444b6a3804048d7b45680
Title: Mega Gattling Pea
*/

import React, { forwardRef, Suspense } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';
import megagattlingpea from '../assets/models/mega_gattling_pea.glb'

const MegaGattlingPeaModel = forwardRef((props, ref) => {
  const { currentColor } = props;
  const { nodes, materials } = useGLTF(megagattlingpea)
  return (
    <group scale={0.5} ref={ref} {...props} dispose={null}>
      <group 
      rotation={[-Math.PI/2, 0, -Math.PI/1]}
      >
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} 
        // material-color={currentColor}
        />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} 
        // material-color={currentColor}
        />
      </group>
    </group>
  )
})

MegaGattlingPeaModel.displayName = 'MegaGattlingPeaModel';

useGLTF.preload(megagattlingpea)

const MegaGattlingPeaModelWrapper = forwardRef((props, ref) => (
  <Suspense fallback={null}>
    <MegaGattlingPeaModel ref={ref} {...props} />
  </Suspense>
));

MegaGattlingPeaModelWrapper.displayName = 'MegaGattlingPeaModelWrapper';

export { MegaGattlingPeaModelWrapper as MegaGattlingPeaModel };