/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 rubiks_cube.glb 
Author: BeyondDigital (https://sketchfab.com/BeyondDigital)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubiks-cube-d7d8aa83720246c782bca30dbadebb98
Title: Rubik's Cube
*/

import React, { forwardRef, Suspense } from 'react'
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei'
import rubikscube from '../assets/models/rubiks_cube.glb'

const RubiksCubeModel = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF(rubikscube)

  const material = new THREE.MeshPhysicalMaterial({
    metalness: 0.0,
    roughness: 0.9,
    clearcoat: .1,
    clearcoatRoughness: .9,
    transparent: false,
    side: THREE.DoubleSide,
    wireframe: false,
  });

  return (
    <group ref={ref} {...props} dispose={null}>
      <group scale={0.005}>
        <mesh geometry={nodes.Baked_baked_0.geometry} material={materials.baked} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
});

RubiksCubeModel.displayName = 'RubiksCubeModel';

useGLTF.preload(rubikscube)

const RubiksCubeModelWrapper = forwardRef((props, ref) => (
  <Suspense fallback={null}>
    <RubiksCubeModel ref={ref} {...props} />
  </Suspense>
));

RubiksCubeModelWrapper.displayName = 'RubiksCubeModelWrapper';

export { RubiksCubeModelWrapper as RubiksCubeModel };