/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 sunglasses.glb 
Author: BitGem (https://sketchfab.com/bitgem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/deal-with-it-sunglasses-cd4d5594a09d422b9c588dd9941476d9
Title: Deal With It Sunglasses
*/

import React, { Suspense, forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import sunglasses from '../assets/models/sunglasses.glb'

const SunglassesModel = forwardRef((props, ref) => {
  const { currentColor } = props;
  const { nodes, materials } = useGLTF(sunglasses)
  return (
    <group {...props} ref={ref} dispose={null} >
    <group scale={.03} position={[2,0.05,0.275]}>
      <mesh geometry={nodes.black_mesh_black_0.geometry} material={materials.black} />
      <mesh geometry={nodes.white_mesh_white_0.geometry} material={materials.white} material-color={currentColor} />
    </group>
    </group>
  )
})

SunglassesModel.displayName = 'SunglassesModel';

useGLTF.preload(sunglasses)

const SunglassesModelWrapper = forwardRef((props, ref) => (
  <Suspense fallback={null}>
    <SunglassesModel ref={ref} {...props} />
  </Suspense>
));

SunglassesModelWrapper.displayName = 'SunglassesModelWrapper';

export { SunglassesModelWrapper as SunglassesModel };